### ISSUE TITLE
Credentials are not stored, system prompts to manually type user and password on every boot

### ISSUE THREAD

**Issue by csolisr** [YunoHost-Apps/vpnclient_ynh#99] opened 2022-05-04 15:43 UTC
### Describe the bug

When using the application to configure the server to connect to an OpenVPN server automatically, the credentials are ignored, instead requesting the user to type them manually through the terminal. This defeats the point of storing the credentials, as it requires manual intervention every time the VPN goes down.

### Context

- Hardware: Dedicated x86 board
- YunoHost version: 11.0.6
- I have access to my server: Through SSH, webadmin, direct access
- Are you in a special context or did you perform some particular tweaking on your YunoHost instance?: no
- Using, or trying to install package version/branch: 2.0.2

### Steps to reproduce

- Install the VPN Client app
- Configure the application through the web administrator:
  - Load a .ovpn / .cube file
  - Insert the user and password
  - Click save

### Expected behavior

The system should take the credentials and store them for future usage.

### Actual behavior

The system ignores the stored credentials and immediately requests the user and password through the terminal:

```
Broadcast message from root@example.net:
Password entry required for 'Enter Auth Username:' (PID 12345). Please enter password with the systemd-tty-ask-password-agent tool!
```

So I need to run `sudo systemd-tty-ask-password-agent` twice, once to enter the user name and again to enter the password.

### Logs

Relevant lines from `journalctl -u openvpn@client.service`:

```
May 03 19:49:01 example.net openvpn[12345]: Failed to query password: Timer expired
May 03 19:49:01 example.net systemd[1]: openvpn@client.service: start operation timed out. Terminating
May 03 19:49:01 example.net openvpn-client[12345]: ERROR: Failed retrieving username or password
May 03 19:49:01 example.net openvpn-client[12345]: Exiting due to fatal error
May 03 19:49:01 example.net systemd[1]: openvpn@client.service: Main process exited, code=exited, status=1/FAILURE
May 03 19:49:01 example.net systemd[1]: openvpn@client.service: Failed with result 'timeout'.
May 03 19:49:01 example.net systemd[1]: Failed to start OpenVPN connection to client.
May 03 19:49:01 example.net systemd[1]: openvpn@client.service: Scheduled restart job, restart counter is at 1.
```

**Comment by csolisr** [comment] 2022-05-05 19:53
Just found out that the file `/etc/openvpn/keys/credentials` was somehow not created by the installation tool, nor listed on the `/etc/openvpn/client.conf` file either.

**Comment by hidrarga** [comment] 2024-06-02 10:46
I'm closing, but feel free to open the issue again if the problem is still there.

**Closed by hidrarga** 2024-06-02 10:46 UTC
